### ISSUE TITLE
Multiplier tab breaks with Continuum enabled due to Achievement 183

### ISSUE THREAD

**Issue by James103** [Rangaz/AntimatterDimensionsWithAchievementRewards#26]
**Describe the bug**
When viewing the Multiplier tab with Continuum enabled, "Base AD Production" breaks because "Purchased AD N" fails to calculate as a result of an error thrown in the following line:
https://github.com/Rangaz/AntimatterDimensionsWithAchievementRewards/blob/bfb4398d04e1ed43553692e0245d0d1ad1ff7f51/src/core/secret-formula/multiplier-tab/antimatter-dimensions.js#L67

The error is:
```
04:16:36.338 Uncaught (in promise) TypeError: AntimatterDimension(...).continuumValue.timesEffectOf is not a function
    t antimatter-dimensions.js:67
    multValue antimatter-dimensions.js:78
    multValue antimatter-dimensions.js:78
    Ij breakdown-entry-info.js:93
    get mult breakdown-entry-info.js:47
    get isVisible breakdown-entry-info.js:87
    update breakdown-entry-info.js:33
    update MultiplierBreakdownEntry.vue:114
    dispatch event-hub.js:26
    flushEvents ui.js:143
27 antimatter-dimensions.js:67:49
```

**To Reproduce**
1. Unlock the sixth Celestial and enable Continuum.
2. View the Multiplier Tab, specifically the "Antimatter Production" or "Antimatter Dimensions" subtabs.
3. Notice they both display no information and instead falsely say that the total effect is disabled, inactive, or reduced to 1.

**Expected behavior**
The multiplier breakdown should work properly for these tabs.

**Savefile**
[AD Rewarded predoom.txt](https://github.com/user-attachments/files/16039482/AD.Rewarded.predoom.txt)

**Comment by Rangaz** [comment]
I have launched a fix. Thank you for reporting!
