### ISSUE TITLE
Inconsistencies in Enhancement wording

### ISSUE THREAD

**Issue by James103** [Rangaz/AntimatterDimensionsWithAchievementRewards#28]
**Describe the bug**
"This Enhancement free" should be "This Enhancement **is** free" here: https://github.com/Rangaz/AntimatterDimensionsWithAchievementRewards/blob/40da770d4c83a6252e340e3ac7616642d7ddfae4/src/core/secret-formula/achievements/normal-achievements.js#L136

"This Enhancement is" should be "This Enhancement is **free**" here: https://github.com/Rangaz/AntimatterDimensionsWithAchievementRewards/blob/40da770d4c83a6252e340e3ac7616642d7ddfae4/src/core/secret-formula/achievements/normal-achievements.js#L796

"This costs 2 Achievements" should say "This costs 2 **Enhancements**" here: https://github.com/Rangaz/AntimatterDimensionsWithAchievementRewards/blob/40da770d4c83a6252e340e3ac7616642d7ddfae4/src/core/secret-formula/achievements/normal-achievements.js#L1744

**To Reproduce**
Unlock the ACHEH perk, then fully complete Hard V and check the relevant achievement tooltips for the inconsistent grammar.

**Expected behavior**
No such inconsistencies

**Savefile**
[AD Rewarded predoom.txt](https://github.com/user-attachments/files/16039482/AD.Rewarded.predoom.txt)

**Comment by Rangaz** [comment]
Thank you for reporting! They have been fixed!
